### ISSUE TITLE
Sao Paulo region is not supported

### ISSUE THREAD

**Issue by minzetao-tc** [hashicorp/packer-plugin-tencentcloud#63]
I found Tencent Cloud recently released a new region, Sao Paulo, and I tried to create an image in this region, but found it is not supported on Packer. Is it possible to add this new region to Packer?

**Comment by minzetao-tc** [comment]
This new region code should be sa-saopaulo. I got it from here: https://intl.cloud.tencent.com/document/product/239/4106#other-countries-and-regions

**Comment by likexian** [comment]
Hello @minzetao-tc 
The PR about this has been merged, refer: https://github.com/hashicorp/packer-plugin-tencentcloud/pull/62
We should wait for @azr to release it.

**Comment by likexian** [comment]
Hello @minzetao-tc 
Please try the latest version.

**Comment by nywilken** [comment]
Closing as this request was merged in #62, and since been released.
