### ISSUE TITLE
The force option is no longer working

### ISSUE THREAD

**Issue by smorimoto** [hashicorp/packer-plugin-tencentcloud#65]
#### Overview of the Issue

ssia.

#### Reproduction Steps

```
packer build -force .
```

### Plugin and Packer version

`Packer v1.8.0`

### Simplified Packer Buildfile

```hcl
packer {
  required_plugins {
    docker = {
      version = "1.0.4"
      source  = "github.com/hashicorp/tencentcloud"
    }
  }
}

variable "secret_id" {
  type    = string
  default = env("TENCENTCLOUD_SECRET_ID")
}

variable "secret_key" {
  type    = string
  default = env("TENCENTCLOUD_SECRET_KEY")
}

source "tencentcloud-cvm" "cvm" {
  associate_public_ip_address = true
  disk_type                   = "CLOUD_PREMIUM"
  image_name                  = "test"
  instance_type               = "S5.MEDIUM2"
  packer_debug                = true
  region                      = "ap-tokyo"
  secret_id                   = var.secret_id
  secret_key                  = var.secret_key
  source_image_id             = "img-eb30mz89"
  ssh_username                = "root"
  zone                        = "ap-tokyo-1"
}

build {
  sources = ["source.tencentcloud-cvm.cvm"]

  provisioner "shell" {
    inline = ["echo \"Hello Word\""]
  }
}
```

**Comment by nywilken** [comment]
Hi @smorimoto can you please provide details on what exactly is not working when using the force flag. If you could take a minute to provide the information requested in the [bug template](https://github.com/hashicorp/packer-plugin-tencentcloud/issues/new?assignees=&labels=bug&template=bug_report.md) it would help us greatly. Thanks!

**Comment by nywilken** [comment]
Hi there 👋 , I'm going to close this issue since there hasn't been any updates to it. But if you are still running into issues please feel free to leave a comment on the issue with the requested information and we will gladly reopen.
